config/routes.rb
Rails.application.routes.draw do
  root "recruitments#top"
  resources :recruitments, only: [:index, :show] do
    resource :entries, only: [:create, :destroy]
    get "entries", to: "entries#index"
    get "confirmation_later", to: "recruitments#confirmation_later"
    get "confirmation_now", to: "recruitments#confirmation_now"
    resources :messages, only: [:create] do
      collection do
        get "reload"
      end
    end
  end
  post "recruitments/later/new", to: "recruitments#new_later"
  post "recruitments/now/new", to: "recruitments#new_now"
  post "recruitments/later/create", to: "recruitments#create_later"
  post "recruitments/now/create", to: "recruitments#create_now"
  post "recruitments/later/edit", to: "recruitments#edit_later"
  post "recruitments/now/edit", to: "recruitments#edit_now"
  post "recruitments/later/update", to: "recruitments#update_later"
  post "recruitments/now/update", to: "recruitments#update_now"
  delete "recruitments/destroy", to: "recruitments#destroy"
  post "recruitments/close", to: "recruitments#close"
  post "recruitments/restart", to: "recruitments#restart"

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  get "profile", to: "users#profile"
  post "profile/update", to: "users#update"
  get "users/search", to: "users#search"

  resources :friends, only: [:index]
  get "friends/mutual", to: "friends#mutual"
  get "friends/oneway_followers", to: "friends#oneway_followers"
  get "friends/oneway_followings", to: "friends#oneway_followings"
  post "friends/:id/heart", to: "friends#heart"
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController
  before_action :signed_in_user_to_recruitments, only: [:top]
  before_action :signed_out_to_root, except: [:top]
  before_action :nil_recruit_to_recruits_path, only: [:show, :confirmation_later, :confirmation_now]
  before_action :recruiter_to_recruits_path, only: [:new_later, :create_later, :new_now, :create_now]
  before_action :not_recruiter_to_recruits_path, only: [:edit_later, :edit_now, :update_later, :update_now, :destroy, :close, :restart]
  before_action :entrant_to_recruits_path, only: [:new_later, :create_later, :new_now, :create_now]

  def top
  end

  # 募集一覧表示画面用アクション
  def index
    recruits_all = Recruit.includes([:user, :later, :now]).order("created_at DESC")
    @recruits_of_friend = []

    #フレンドと自分の募集のみ抽出
    recruits_all.each do |recruit|
      if current_user.friend?(recruit.user) || current_user.my_recruit?(recruit)
        @recruits_of_friend << recruit
      end
    end
  end

  # 「これから」の募集作成UI表示用アクション
  def new_later
    render json: {info: current_user, image: url_for(current_user.image)}
  end
  
  # 「いま」の募集作成UI表示用アクション
  def new_now
    render json: {info: current_user, image: url_for(current_user.image)}
  end

  # 「これから」の募集保存用アクション
  def create_later
    recruit_later = RecruitLater.new(recruit_later_param)
    if recruit_later.valid?
      recruit_later.save
      flash[:success] = "「これから」で募集を作成しました"
    else
      flash[:danger] = "保存に失敗しました"
    end
    redirect_to recruitments_path
  end
  
  # 「いま」の募集保存用アクション
  def create_now
    recruit_now = RecruitNow.new(recruit_now_param)
    if recruit_now.valid?
      recruit_now.save
      flash[:success] = "「いま」で募集を作成しました"
    else
      flash[:danger] = "保存に失敗しました"
    end
    redirect_to recruitments_path
  end
  
  # 「これから」の募集編集UI表示用アクション
  def edit_later
    render json: {info: {recruit: @recruit, later: @recruit.later}, user: {info: @recruit.user, image: url_for(@recruit.user.image)}}
  end
  
  # 「いま」の募集編集UI表示用アクション
  def edit_now
    render json: {info: {recruit: @recruit, now: @recruit.now}, user: {info: @recruit.user, image: url_for(@recruit.user.image)}}
  end

  # 「これから」の募集更新用アクション
  def update_later
    recruit_later = RecruitLater.new(recruit_later_param)
    flash = {}
    if recruit_later.valid?
      recruit_later.update(@recruit)
      flash = flash_hash("success", "募集内容を更新しました")
    else
      flash = flash_hash("danger", "更新に失敗しました")
    end
    render json: {recruit_later: {recruit: @recruit, later: @recruit.later, close: @recruit.close?}, flash: flash}
  end
  
  # 「いま」の募集更新用アクション
  def update_now
    recruit_now = RecruitNow.new(recruit_now_param)
    if recruit_now.valid?
      recruit_now.update(@recruit)
      flash = flash_hash("success", "募集内容を更新しました")
    else
      flash = flash_hash("danger", "更新に失敗しました")
    end
    render json: {recruit_now: {recruit: @recruit, now: @recruit.now, close: @recruit.close?}, flash: flash}
  end

  # 募集のルーム表示用アクション
  def show
    @recruit = Recruit.find(params[:id])
    @messages = @recruit.messages.includes(:sender).order("created_at ASC")
    @message = Message.new
    
    if current_user.my_recruit?(@recruit) #募集作成者であれば
      if @recruit.close?
        @page_name = "マイ募集(募集終了)"
      else
        @page_name = "マイ募集(募集中)"
      end
    elsif current_user.my_entry?(@recruit) #募集の参加者であれば
      if @recruit.close?
        @page_name = "参加中(募集終了)"
      else
        @page_name = "参加中(募集中)"
      end
    else
      redirect_to recruitments_path
    end
  end

  # 募集削除用アクション
  def destroy
    @recruit.users.each do |entrant|
      InquiryMailer.send_mail(nil, entrant, "募集削除通知", "あなたが参加していた募集が削除されました。").deliver_later
    end
    @recruit.destroy
    flash[:success] = "募集を削除しました"
    redirect_to recruitments_path
  end
  
  # 募集終了用アクション
  def close
    if @recruit.update(close_flag: 1)
      flash = flash_hash("success", "募集を終了しました")
    else
      flash = flash_hash("danger", "募集の終了に失敗しました")
    end
    render json: {close_flag: @recruit.close?, flash: flash}
  end
  
  # 募集再開用アクション
  def restart
    @recruit.update(close_flag: 0)
    unless @recruit.max_entry?
      flash = flash_hash("success", "募集を再開しました")
    else
      flash = flash_hash("danger", "募集人数がMAXのため再開できません")
    end
    render json: {close_flag: @recruit.close?, flash: flash}
  end

  # ルーム画面での募集確認用「これから」
  def confirmation_later
    recruit = Recruit.find(params[:recruitment_id])
    if current_user.friend?(recruit.user) || recruit.user.id == current_user.id
      render json: {info: {recruit: recruit, later: recruit.later}, user: {info: recruit.user, image: url_for(recruit.user.image)}}
    end
  end

  # ルーム画面での募集確認用「いま」
  def confirmation_now
    recruit = Recruit.find(params[:recruitment_id])
    if current_user.friend?(recruit.user) || recruit.user.id == current_user.id
      render json: {info: {recruit: recruit, now: recruit.now}, user: {info: recruit.user, image: url_for(recruit.user.image)}}
    end
  end
  
  
  private
  def recruit_later_param
    params.require(:recruit_later).permit(
      :start_at_hour_top,
      :start_at_minute_top,
      :start_at_hour_bottom,
      :start_at_minute_bottom,
      :end_at_hour_top,
      :end_at_minute_top,
      :end_at_hour_bottom,
      :end_at_minute_bottom,
      :place,
      :message,
      :close_condition_count
    ).merge(user: current_user)
  end
  
  def recruit_now_param
    params.require(:recruit_now).permit(
      :member_count,
      :end_at_hour_top,
      :end_at_minute_top,
      :end_at_hour_bottom,
      :end_at_minute_bottom,
      :place,
      :message,
      :close_condition_count
    ).merge(user: current_user)
  end
  
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/views/recruitments/_chat.html.erb
<% if current_user.id == message.sender.id %>
  <div class="my-chat-area chat-content" data-message-id="<%= message.id %>">
    <div class="my-left-wrap">
      <div class="my-chat-time"><%= l message.created_at, format: :hour_minute %></div>
    </div>
    <div class="my-right-wrap">
      <div class="my-chat chat">
        <%= image_tag message.image, class: "attached-image" if message.image.attached? %>
        <%=safe_join(message.text.split("\n"),tag(:br))%>
      </div>
    </div>
  </div>
<% else %>
  <div class="other-chat-area chat-content" data-message-id="<%= message.id %>">
    <div class="other-left-wrap">
      <%= image_tag message.sender.image, class: "other-user-image" %>
    </div>
    <div class="other-center-wrap">
      <div class="other-user-name"><%= message.sender.name %><span>ID:<%= message.sender.id %></span></div>
      <div class="other-chat chat">
        <%= image_tag message.image, class: "attached-image" if message.image.attached? %>
        <%=safe_join(message.text.split("\n"),tag(:br))%>
      </div>
    </div>
    <div class="other-right-wrap">
      <div class="other-chat-time"><%= l message.created_at, format: :hour_minute %></div>
    </div>
  </div>
<% end %>

app/views/recruitments/_form.html.erb
<%= form_with model: recruit, url: recruitments_later_create_path, method: :post, local: :true do |f| %>
  <div class="item-wrap">
    <p class="item-title">募集人数</p>
    <p>※参加人数が募集人数を超えると自動で募集を終了します。</p>
    <%= f.select :close_condition_count, (1..15).to_a, {}, class: 'item-select' %>
  </div>
  <div class="item-wrap">
    <p class="item-title">希望開始時間</p>
    <%= f.select :start_at_hour_top, (0..23).to_a.map { |v| "%02d" % v }, {}, class: 'item-select' %> :
    <%= f.select :start_at_minute_top, [0,15,30,45].map { |v| "%02d" % v }, {}, class: 'item-select' %> ~
    <%= f.select :start_at_hour_bottom, (0..23).to_a.map { |v| "%02d" % v }, {}, class: 'item-select' %> :
    <%= f.select :start_at_minute_bottom, [0,15,30,45].map { |v| "%02d" % v }, {}, class: 'item-select' %>
  </div>
  <div class="item-wrap">
    <p class="item-title">希望終了時間</p>
    <%= f.select :end_at_hour_top, (0..23).to_a.map { |v| "%02d" % v }, {}, class: 'item-select' %> :
    <%= f.select :end_at_minute_top, [0,15,30,45].map { |v| "%02d" % v }, {}, class: 'item-select' %> ~
    <%= f.select :end_at_hour_bottom, (0..23).to_a.map { |v| "%02d" % v }, {}, class: 'item-select' %> :
    <%= f.select :end_at_minute_bottom, [0,15,30,45].map { |v| "%02d" % v }, {}, class: 'item-select' %>
  </div>
  <div class="item-wrap">
    <p class="item-title">希望場所</p>
    <%= f.text_field :place, class:"item-text", placeholder:"最大 20文字まで", maxlength:"20" %>
  </div>
  <div class="item-wrap">
    <p class="item-title">ひとこと</p>
    <%= f.text_field :message, class:"item-text", placeholder:"最大 20文字まで", maxlength:"20" %>
  </div>

  <%= f.submit "作成" ,class:"sell-btn" %>
<% end %>

app/views/recruitments/_later.html.erb
<div class="recruit-info">
  <div class="info-top">
    <div class="recruit-user-name"><%= recruit.user.name %><span>ID: <%= recruit.user.id %></span></div>
    <div class="recruit-type later">これから</div>
    <div class="post-time">投稿時間 <%= l recruit.created_at, format: :hour_minute %></div> 
  </div>
  <ul class="info-bottom">
    <li>
      <div class="recruit-item">希望開始時間</div>
      <div class="recruit-value"><%= "#{recruit.later.start_at_hour_top}:#{recruit.later.start_at_minute_top} ~ #{recruit.later.start_at_hour_bottom}:#{recruit.later.start_at_minute_bottom}" %></div>
    </li>
    <li>
      <div class="recruit-item">希望終了時間</div>
      <div class="recruit-value"><%= "#{recruit.later.end_at_hour_top}:#{recruit.later.end_at_minute_top} ~ #{recruit.later.end_at_hour_bottom}:#{recruit.later.end_at_minute_bottom}" %></div>
    </li>
    <li>
      <div class="recruit-item">希望場所</div>
      <div class="recruit-value"><%= recruit.later.place %></div>
    </li>
    <li>
      <div class="recruit-item">ひとこと</div>
      <div class="recruit-value"><%= recruit.later.message %></div>
    </li>
  </ul>
</div>

app/views/recruitments/_now.html.erb
<div class="recruit-info">
  <div class="info-top">
    <div class="recruit-user-name"><%= recruit.user.name %><span>ID: <%= recruit.user.id %></span></div>
    <div class="recruit-type now">いま</div>
    <div class="post-time">投稿時間 <%= l recruit.created_at, format: :hour_minute %></div>
  </div>
  <ul class="info-bottom">
    <li>
      <div class="recruit-item">現在の人数</div>
      <div class="recruit-value"><%= "#{recruit.now.member_count}人" %></div>
    </li>
    <li>
      <div class="recruit-item">終了予定時間</div>
      <div class="recruit-value"><%= "#{recruit.now.end_at_hour_top}:#{recruit.now.end_at_minute_top} ~ #{recruit.now.end_at_hour_bottom}:#{recruit.now.end_at_minute_bottom}" %></div>
    </li>
    <li>
      <div class="recruit-item">現在の場所</div>
      <div class="recruit-value"><%= recruit.now.place %></div>
    </li>
    <li>
      <div class="recruit-item">ひとこと</div>
      <div class="recruit-value"><%= recruit.now.message %></div>
    </li>
  </ul>
</div>

app/views/recruitments/_recruit.html.erb
<% if current_user.my_recruit?(recruit) %> <%# 自身の募集であればIDを付与 %>
  <div class="recruit-wrap" id="current_user_recruit">
<% else %>
  <div class="recruit-wrap">
<% end %>
  <% if recruit.close? %>
    <div class="close-label">募集が終了しました</div>
  <% end %>
  <div class="recruit-detail">
    <%= image_tag recruit.user.image, class: "recruit-user-image" %>
    <% if recruit.later.present? %> <%# 募集タイプが「これから」の場合 %>
      <%= render partial: "later", locals: {recruit: recruit} %>
    <% else %>  <%# 募集タイプが「いま」の場合 %>
      <%= render partial: "now", locals: {recruit: recruit} %>
    <% end %>
    <div class="menu-btn-wrap">
      <% if current_user.my_recruit?(recruit) %> <%# 自身の募集であれば表示 %>
        <i id="menu-btn" class="fas fa-ellipsis-v menu-btn"></i>
        <div id="recruit-menu-content" class="recruit-menu-content">
          <% if recruit.later.present? %> <%# 募集タイプが「これから」の場合 %>
            <div class="recruit-menu-item" id="edit-later">編集</div>
          <% else %>  <%# 募集タイプが「いま」の場合 %>
            <div class="recruit-menu-item" id="edit-now">編集</div>
          <% end %>
          <% if recruit.close? %>  <%# 募集が終了している場合 %>
            <div class="recruit-menu-item" id="close" data-status="restart">募集再開</div>
          <% else %>  <%# 募集が終了していない場合 %>
            <div class="recruit-menu-item" id="close" data-status="close">募集終了</div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="entry-wrap">
    <i class="fas fa-user-circle entry-count" data-recruit-id=<%= recruit.id %>><span id="entry-num"><%= recruit.entries.length %>/</span><span id="recruit-count"><%= recruit.close_condition_count %></span></i>
    <% if current_user.recruit? %> <%# ログインユーザーが募集をしていれば表示 %>

      <% if current_user.my_recruit?(recruit) %> <%# 自身の募集であれば表示 %>
        <%= link_to "マイ募集ルーム", recruitment_path(recruit), class: "btn submit-btn recruit-room-btn" %>
      <% else %> <%# 自身の募集でなければ表示 %>
        <div class="disable">マイ募集が存在する間は参加できません</div>
      <% end %>

    <% else %> <%# ログインユーザーが募集をしていなければ表示 %>

      <% if current_user.entry? %> <%# ログインユーザーが参加をしていれば表示 %>
        <% if current_user.my_entry?(recruit) %> <%# 自身が参加している募集であれば表示 %>
          <%= link_to "参加中のルーム", recruitment_path(recruit), class: "btn submit-btn recruit-room-btn" %>
        <% else %> <%# 自身が参加している募集でなければ表示 %>
          <div class="disable">他の募集に参加中</div>
        <% end %>
      <% elsif !recruit.close? %> <%# ログインユーザーが参加をしていない、かつ、募集終了していなければ表示 %>
        <%= link_to "参加", recruitment_entries_path(recruit), method: :post, class: "btn other-btn" %>
      <% end %>

    <% end %>
  </div>
</div>

app/views/recruitments/index.html.erb
<%= render partial: 'shared/header', locals: { page_name: "募集一覧" } %>

<div class="main">
  <div class="recruits-container">

    <% if current_user.matchers.length <= 0 %> <%# フレンドが存在しない時 %>
      <div class="no-friends">
        <p>
          フレンドになったユーザーの募集が表示されます。<br>まずはフレンドを追加しましょう。
        </p>
        <%= link_to "フレンドを追加する", friends_path, class: "btn" %>
      </div>
    <% else %> <%# フレンドが存在する時 %>
      <% if @recruits_of_friend.length <= 0 %> <%# 募集が存在しない時 %>
        <div class="no-recruits">
          <p>本日はまだ誰も募集していません。</p>
        </div>
      <% else %> <%# 募集が存在する時 %>
        <%= render partial: "recruit", collection: @recruits_of_friend %>
      <% end %>
      <div class="back" id="back"></div>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/recruitments/show.html.erb
<%= render partial: 'shared/header', locals: { page_name: @page_name } %>

<div class="recruits-confirmation" id="recruits-confirmation" data-recruit-id="<%= @recruit.id %>"></div>

<div class="main-room">

  <div class="chat-main" id="chat-main">
    <%= render partial: 'chat', collection: @messages, as: :message %>
  </div>

  <%= form_with model: @message, url: recruitment_messages_path(@recruit), class: "chat-bar", id: "chat-bar", local: true do |f| %>
    <div id="image-list"></div>
    <div class="chat-wrap">
      <div class="flex-area">
        <div class="flex-area-dummy" aria-hidden="true"></div>
        <%= f.text_area :text, placeholder: "メッセージを入力", class: "chat-area", rows: "1" %>
      </div>
      <label>
        <i class="fas fa-file-image file-attach-btn"></i>
        <%= f.file_field :image, class: "hidden" %>
      </label>
      <%= f.submit "送信" , class: "send-btn", id: "send-btn"%>
    </div>
  <% end %>

  <div class="back" id="back"></div>
</div>

app/views/recruitments/top.html.erb
<%= render partial: 'shared/header', locals: { page_name: "" } %>

<div class="main">
  <div class="top-image">
    <div class="top-title-wrap">
      <h1 class="top-title">今日飲みたい。</h1>
      <p class="top-message">
        突然込みあげるこの気持ち。<br>
        同じ気持ちの友人を見つけて、<br>
        <span>即席</span>で飲み会を開いちゃいましょう！
      </p>
    </div>

    <div class="top-login-wrap">
      <%= link_to image_tag('google_icon.png') + "Sign in with Google", user_google_oauth2_omniauth_authorize_path, method: :post, class: "top-login-btn"%>
      <p class="top-login-text">※新規登録、ログインのどちらも上記のリンクから行うことができます。</p>
    </div>
  </div>

  <div class="about-container">
    <div class="about-title">
      飲み仲間をみつけよう
    </div>
    <ul class="about-tab-wrap">
      <li class="about-tab select-tab" id="friend-add-tab">フレンドを追加</li>
      <li class="about-tab" id="recruit-create-tab">募集を作成</li>
      <li class="about-tab" id="entry-tab">募集に参加</li>
      <li class="about-tab" id="message-tab">メッセージでやり取り</li>
    </ul>
    <div class="about-content">
      <div class="change" id="previous">
        <i class="fas fa-chevron-left"></i>
      </div>
      <div class="about-item" id="about-item">
        <img src="gifs/friend_add.gif" alt="フレンド追加" class="">
        <div class="about-descript">
          <p class="main-descript"><span class="heart">ハート</span>をクリックして<br>フレンドを作ろう</p>
          <p class="sub-descript">
            フレンド画面でユーザーに<span class="heart">ハート</span>を付与しましょう。<br>
            お互いに<span class="heart">ハート</span>を付け合うことでフレンドとなります。<br>
            フレンドとなったユーザーには、あなたが作成した募集が表示されます。
          </p>
        </div>
      </div>
      <div class="change" id="next">
        <i class="fas fa-chevron-right"></i>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>