config/routes.rb
Rails.application.routes.draw do
  root "recruitments#top"
  resources :recruitments, only: [:index, :show] do
    resource :entries, only: [:create, :destroy]
    get "entries", to: "entries#index"
    get "confirmation_later", to: "recruitments#confirmation_later"
    get "confirmation_now", to: "recruitments#confirmation_now"
    resources :messages, only: [:create] do
      collection do
        get "reload"
      end
    end
  end
  post "recruitments/later/new", to: "recruitments#new_later"
  post "recruitments/now/new", to: "recruitments#new_now"
  post "recruitments/later/create", to: "recruitments#create_later"
  post "recruitments/now/create", to: "recruitments#create_now"
  post "recruitments/later/edit", to: "recruitments#edit_later"
  post "recruitments/now/edit", to: "recruitments#edit_now"
  post "recruitments/later/update", to: "recruitments#update_later"
  post "recruitments/now/update", to: "recruitments#update_now"
  delete "recruitments/destroy", to: "recruitments#destroy"
  post "recruitments/close", to: "recruitments#close"
  post "recruitments/restart", to: "recruitments#restart"

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  get "profile", to: "users#profile"
  post "profile/update", to: "users#update"
  get "users/search", to: "users#search"

  resources :friends, only: [:index]
  get "friends/mutual", to: "friends#mutual"
  get "friends/oneway_followers", to: "friends#oneway_followers"
  get "friends/oneway_followings", to: "friends#oneway_followings"
  post "friends/:id/heart", to: "friends#heart"
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :signed_out_to_root

  def index
    @friends = current_user.matchers
  end
  
  #フレンドユーザー情報を返す
  def mutual
    image_in_friends = [];
    friends = current_user.matchers
    friends.each do |friend|
      image_in_friends << {info: friend, image: url_for(friend.image), follower_flag: current_user.follower?(friend)}
    end
    render json: image_in_friends
  end
  
  #ログイン中のユーザーから一方的にハートを押されているユーザー情報を取得
  def oneway_followers
    image_in_friends = [];
    friends = current_user.oneway_followers
    friends.each do |friend|
      image_in_friends << {info: friend, image: url_for(friend.image), follower_flag: current_user.follower?(friend)}
    end
    render json: image_in_friends
  end
  
  #ログイン中のユーザーに対して一方的にハートを押しているユーザー情報を取得
  def oneway_followings
    image_in_friends = [];
    friends = current_user.oneway_followings
    friends.each do |friend|
      image_in_friends << {info: friend, image: url_for(friend.image), follower_flag: current_user.follower?(friend)}
    end
    render json: image_in_friends
  end
  
  #ハートをクリックした際のアクション
  def heart
    target_user = User.find(params[:id])

    if current_user.follower?(target_user) #target_userのハートが付与された状態？
      flash = heart_delete(target_user)
    else #target_userのハートが解除された状態？
      flash = heart_create(target_user)
    end

    render json: {heart: current_user.follower?(target_user), flash: flash}
  end
  

  private

  # ハートを解除するメソッド
  def heart_delete(target_user)
    if target_user.recruit? && current_user.my_entry?(target_user.recruit?) # target_userの募集に参加しているか
      flash = flash_hash("danger", "#{target_user.name}   の募集に参加中のため解除できません")
    elsif current_user.recruit? && target_user.my_entry?(current_user.recruit?)
      flash = flash_hash("danger", "マイ募集の参加者は解除できません")
    elsif current_user.unfollow(target_user) #ハートの解除に成功したか
      flash = flash_hash("success", "#{target_user.name}   への申請を取り消しました")
      if current_user.following?(target_user) #target_userからハートを付与されているか
        flash = flash_hash("success", "#{target_user.name}   がフレンドから解除されました")
      end
      if current_user.recruit? &&current_user.matchers.length <= 0 #フレンドが0人になったか
        current_user.recruit?.destroy
      end
    else
      flash = flash_hash("danger", "ハートの解除に失敗しました")
    end

    flash
  end

  # ハートを付与するメソッド
  def heart_create(target_user)
    if current_user.follow(target_user) #ハートを付与する
      flash = flash_hash("success", "#{target_user.name}   にフレンド申請しました")
      mail_subject = "フレンド依頼通知"
      mail_message = "があなたにフレンド依頼をしました。"
      if current_user.following?(target_user)
        flash = flash_hash("success", "#{target_user.name}   がフレンドに追加されました")
        mail_subject = "フレンド追加通知"
        mail_message = "があなたとフレンドになりました。"
      end
      InquiryMailer.send_mail(current_user, target_user, mail_subject, mail_message).deliver_later
    else
      flash = flash_hash("danger", "ハートの付与に失敗しました")
    end

    flash
  end
  
  
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/index.html.erb
<%= render partial: 'shared/header', locals: { page_name: "フレンド" } %>

<div class="main">
  <div class="friend-container">
    <ul class="friend-tab-wrap">
      <li id="list-tab" class="friend-tab select-tab">フレンド一覧</li>
      <li id="applying-tab" class="friend-tab">フレンド申請中</li>
      <li id="approval-pending-tab" class="friend-tab">フレンド依頼</li>
      <li id="user-search-tab" class="friend-tab">ユーザー検索</li>
    </ul>

    <div id="form-container">
      <%= form_with(url: users_search_path, local: true, method: :get, id: "search-form", class: "search-form") do |form| %>
        <%= form.text_field :keyword, placeholder: "ユーザーIDを入力", id: "search-input", class: "search-input" %>
        <%= form.submit "検索", id: "search-btn", class: "search-btn", disabled: :true %>
      <% end %>
    </div>

    <div id="list-wrap" class="list-wrap">
      <% if @friends.present? %>
        <% @friends.each do |friend| %>
          <div class="list-user-content">
            <%= image_tag friend.image, id: "list-#{friend.id}-image", class: "list-user-image" %>
            <div class="list-user-name">
              <%= friend.name %><span>ID:<%= friend.id %></span>
            </div>
            <div class="list-user-heart">
              <% if current_user.follower?(friend) %>
                <i class="fas fa-heart fa-3x good" data-id=<%= friend.id %>></i>
              <% else %>
                <i class="fas fa-heart fa-3x" data-id=<%= friend.id %>></i>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p class="empty-message">フレンドが存在しません</p>
        <p class='guide'>※お互いにハートを付けることで、フレンドとして登録されます。</p>
      <% end %>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>