config/routes.rb
Rails.application.routes.draw do
  root "recruitments#top"
  resources :recruitments, only: [:index, :show] do
    resource :entries, only: [:create, :destroy]
    get "entries", to: "entries#index"
    get "confirmation_later", to: "recruitments#confirmation_later"
    get "confirmation_now", to: "recruitments#confirmation_now"
    resources :messages, only: [:create] do
      collection do
        get "reload"
      end
    end
  end
  post "recruitments/later/new", to: "recruitments#new_later"
  post "recruitments/now/new", to: "recruitments#new_now"
  post "recruitments/later/create", to: "recruitments#create_later"
  post "recruitments/now/create", to: "recruitments#create_now"
  post "recruitments/later/edit", to: "recruitments#edit_later"
  post "recruitments/now/edit", to: "recruitments#edit_now"
  post "recruitments/later/update", to: "recruitments#update_later"
  post "recruitments/now/update", to: "recruitments#update_now"
  delete "recruitments/destroy", to: "recruitments#destroy"
  post "recruitments/close", to: "recruitments#close"
  post "recruitments/restart", to: "recruitments#restart"

  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  get "profile", to: "users#profile"
  post "profile/update", to: "users#update"
  get "users/search", to: "users#search"

  resources :friends, only: [:index]
  get "friends/mutual", to: "friends#mutual"
  get "friends/oneway_followers", to: "friends#oneway_followers"
  get "friends/oneway_followings", to: "friends#oneway_followings"
  post "friends/:id/heart", to: "friends#heart"
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
     <div class="common notice">
      <%= message %>
     </div>
  <% elsif message_type == "success" %>
     <div class="common success">
      <%= message %>
     </div>
  <% elsif message_type == "danger" %>
     <div class="common danger">
      <%= message %>
     </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <h1>@MORIKEN's PRODUCT.</h1>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="header-wrap">
    <div class="left">
      <%= link_to "instakt", root_path %>
      <% if page_name.present? %>
        <span id="page_name"><%= page_name %></span>
      <% end %>
    </div>

    <div class="right">
      <% if user_signed_in? %> <%# ログイン状態であれば %>
        <% if current_page?(controller: :recruitments, action: :index) %> <%# 現在のページが募集一覧画面であれば %>
          <%= render partial: "shared/header_recruit_index" %>
        <% elsif @recruit.present? && current_page?(controller: :recruitments, action: :show, id: @recruit.id) %> <%# 現在のページがルーム画面であれば %>
          <%= render partial: "shared/header_recruit_show", locals: {recruit: @recruit} %>
        <% end %>
        
        <div class="user-icon-wrap">
          <%= image_tag current_user.image, id: "user-icon", class: "user-icon" %>
          <div class="menu-list" id="user-menu">
            <%= link_to "プロフィール", profile_path, class: "menu" %>
            <%= link_to "フレンド", friends_path, class: "menu" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "menu" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <%= render 'shared/flash_messages' %>
</header>

app/views/shared/_header_recruit_index.html.erb
<% current_user_recruit = current_user.recruit? %>
<% current_user_entry = current_user.entry? %>

<% if current_user.matchers.length > 0 %> <%# フレンドが1人以上かつ、現在のページが募集一覧であれば %>
  <% if current_user_recruit %> <%# 募集中であれば %>
    <%= link_to "マイ募集ルーム", recruitment_path(current_user_recruit), class: "btn submit-btn recruit-room-btn" %>
  <% elsif current_user_entry %> <%# 参加していれば %>
    <%= link_to "参加中のルーム", recruitment_path(current_user_entry.recruit), class: "btn submit-btn recruit-room-btn" %>
  <% else %> <%# 募集も参加もしていなければ %>
    <div class="new-recruit-wrap">
      <div class="btn submit-btn new-recruit-btn" id="modal_btn">募集する</div>
      <ul class="menu-list" id="btn-menu">
        <li class="menu" id="recruit-later">これから</li>
        <li class="menu" id="recruit-now">いま</li>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/shared/_header_recruit_show.html.erb
<% current_user_recruit = current_user.recruit? %>
<% current_user_entry = current_user.entry? %>

<i class="fas fa-user-circle entry-count" data-recruit-id=<%= recruit.id %>><span id="entry-num"><%= recruit.entries.length %>/</span><span id="header-recruit-count"><%= recruit.close_condition_count %></span></i>
<div class="new-recruit-wrap">
  <i class="fas fa-cog header-config" id="modal_btn"></i>
  <ul class="menu-list" id="btn-menu">
    <% if recruit.later.present? %> <%# 募集タイプが「これから」の場合 %>
      <li class="menu" id="confirmation-later">募集内容</li>
    <% else %>  <%# 募集タイプが「いま」の場合 %>
      <li class="menu" id="confirmation-now">募集内容</li>
    <% end %>
    <% if current_user_recruit %> <%# 現在のページがマイ募集ルームであれば %>
      <% if recruit.later.present? %> <%# 募集タイプが「これから」の場合 %>
        <div class="menu" id="edit-later">募集編集</div>
      <% else %>  <%# 募集タイプが「いま」の場合 %>
        <div class="menu" id="edit-now">募集編集</div>
      <% end %>
      <% if current_user_recruit.close? %>  <%# 募集が終了している場合 %>
      <div class="menu" id="close" data-status="restart">募集再開</div>
      <% else %>  <%# 募集が終了していない場合 %>
      <div class="menu" id="close" data-status="close">募集終了</div>
      <% end %>
    <div class="menu" id="recruit-delete">募集削除</div>
    <% elsif current_user_entry %> <%# 現在のページが参加中のルームであれば %>
    <div class="menu" id="entry-delete" data-recruit-id="<%=current_user_entry.recruit.id%>">参加取り消し</div>
    <% end %>
  </ul>
</div>